### ISSUE TITLE
README does not describe how to quick start with the tool

### ISSUE THREAD

**Issue by svetasmirnova** [ihanick/mysqlpat#5]
Currently README describes how to aggregate data from several files, but does not describe how to use the tool.

Add to README usage instructions:

cd to the directory where pt-stalk output is located
run mysqlpat from it
go to File menu, choose Open
Choose mysqladmin file in the dialog
 File->Choose Curves->Commands
Then you can add further graphs from "Graphs" menu

Additionally you can add vmstat outputs using File->Add File->choose vmstat

**Comment by ihanick** [comment]
Also fixed by 146049c6de2b80ee48260df2b3651d202542320a
